config/routes.rb
Rails.application.routes.draw do
  

  resources :memberships, only: [:create]
  resources :shortlists, only: [:create, :destroy, :index]

  resources :song_stats do
      collection { post :import }
  end

  resources :transaction_logs
  resources :subscriptions, only: [:update, :destroy]
  resources :subscription_items, only: [:create, :update, :destroy]

  resources :songs do
    collection { get :all_index }
  end

  resources :albums

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
  resources :users, only: [:show, :update, :edit]

  get 'static_pages/home'
  get 'after_signup_home', to: "static_pages#after_signup_home"
  get 'inactive_signup_home', to: "static_pages#inactive_signup_home"
  get 'about', to: "static_pages#about"
  get 'faq', to: "static_pages#faq"
  get 'contact', to: "static_pages#contact"
  get 'updates', to: "static_pages#updates"
  get 'letter', to: "static_pages#letter"
  get 'pricing', to: "static_pages#pricing"
  get 'dashboard', to: "static_pages#dashboard"
  get 'terms', to: "static_pages#terms"
  get 'cart_page', to: "static_pages#cart_page"
  get 'payment_page', to: "static_pages#payment_page"
  get 'post_login_home', to: "static_pages#post_login_home"
  get 'discover', to: "static_pages#discover"
  get 'performance', to: "static_pages#performance"
  get 'wallet', to: "static_pages#wallet"
  get 'holdings', to: "static_pages#holdings"
  get 'opentrades', to: "static_pages#open_trades"

  get 'membership', to: "static_pages#membership"
  get 'renewals', to: "static_pages#renewals"

  resources :bids, only: [:create, :update, :destroy]
  resources :offers, only: [:create, :update, :destroy]

  root 'static_pages#home'
  get 'albums/:id/album_song' => 'albums#album_song_show', as: :album_song

  resources :payments, only: [:new, :create]
  post 'express_checkout' => 'payments#express_checkout', as: :express_checkout
  post 'confirm_withdrawl' => 'payments#confirm_withdrawl', as: :confirm_withdrawl
  get 'initiate_withdrawl_email_verification' => 'payments#initiate_withdrawl_email_verification', as: :initiate_withdrawl_email_verification

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  # before_filter :authenticate_user!, only: [:cart_page, :payment_page, :discover, :fund, :wallet, :shortlist, :holdings, :open_trades, :performance]
  before_action :authenticate_user!, except: [:home, :about, :faq, :pricing, :contact, :terms, :updates, :letter, :after_signup_home, :inactive_signup_home]
  before_action :mobile_format, only: [:home]
  before_action :authorize_musician, only: [:cart_page, :renewals]

  def home
    if user_signed_in?
      redirect_to post_login_home_url
    else
      render :layout => false
    end
  end

  def about
  end

  def faq
  end

  def pricing
  end

  def contact
  end

  def terms
  end

  def updates
    redirect_to "https://docs.google.com/a/alphabeatsmusic.com/forms/d/1kNieUkKV9GTG-_uAWE1h6DuTJKXBuODGnrOyhTIXMD8/viewform"
  end
  
  def letter
  end

  def dashboard
    @albums = current_user.albums.all
  end
  
  def cart_page
    @albums = current_user.albums.all
  end

  def payment_page
  end

  def post_login_home
  end

  def after_signup_home
  end

  def inactive_signup_home
  end

  def discover
    @songs = (AlbumAddon.paid_songs_list - current_user.shortlist_songs).paginate(:page => params[:page], :per_page => 10)
    #Added config/initializers/array_paginate.rb to make paginate work with arrays
  end

  def wallet
  end

  # def shortlist
  #   @songs = current_user.shortlist_songs
  # end

  def holdings
    @songs = current_user.shareholder_songs
    @offers = current_user.offers.order(updated_at: :desc)
  end

  def performance
    @trade_sells = TradeLog.where(seller_id: current_user.id)
    @trade_buys = TradeLog.where(buyer_id: current_user.id)
    # byebug
  end

  def open_trades
    @bids = current_user.bids.where(open_status: [1,3] )
    @offers = current_user.offers.where(open_status: [1,3])
  end


  def membership
  end

  def renewals
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_continue.html.erb
<div id="continue">
  <% if current_subscription_order.subscription_items.count!=0 %>
    <%=raw("<div class='row'>
      <div class='col-sm-offset-9 col-sm-3'>
        <a href='#{payment_page_path}'>
          <div class='signup-updates'>
            <button class='btn btn-lg solid-button'>
              <span id='updates'>Continue</span>
            </button>
          </div>
        </a>
      </div>") %>
  <% end %>
</div>

app/views/static_pages/_discover_pagination.html.erb
<div class="page_info">
  <%= page_entries_info @songs %>
</div>
<%= will_paginate @songs, :container => false %>

app/views/static_pages/_footer.html.erb
<footer class="footer">

	<div class=<%= Width::CONTAINER %>>
    <div class="row">
        <div class="col-lg-12">
            <h4><a href="mailto:s+email@alphabeatsmusic.com">If you experience any difficulties or notice any errors, please send us a screenshot or description <i class="fa fa-envelope-o gmlogo"></i></a></h4>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <br>
            <li><p>Copyright &copy; Alphabeats Limited | The Black Church, St Mary's Place | Dublin 7, Ireland</p></li>
        </div>
    </div>
    </div>


</footer>

app/views/static_pages/_total_show.html.erb
<div id="payment_page">
  <div class="total_show row col-md-offset-1 col-md-10">

    <div class="total-show-display">
    <% if !current_subscription_order.subscription_items.nil? %>
       <% @total = 0 %>
        <% if current_user.transaction_logs.empty? %>
           <% @total = (@total+0).round(2) %> 
           <div class="row">
            <div class="col-md-6">
              <%= raw("Annual Upload Fee* :")%> 
            </div>
            <div class="col-md-offset-4 col-md-2">
              <%= raw("$20")%> 
            </div>
           </div>
           <div class="row">
            <div class="col-md-6">
              <%= raw("Discount until 12/02/16 :")%> 
            </div>
            <div class="col-md-offset-4 col-md-2">
              <%= raw("-$20")%> 
            </div>
           </div>
        <% else %>
        <% end %>
       <% current_subscription_order.subscription_items.each do |subscription_item| %>
       <% if subscription_item.itemable_type=='AlbumAddon' && subscription_item.itemable.album.songs.count==1 %> <br>
       <b><%= raw("Charges for #{subscription_item.itemable.album.album_name} <br/>") %></b>
       <%# <% @total = @total+12 if !subscription_item.itemable.album.songs.last.self_written  %>
       <% if !subscription_item.itemable.album.songs.last.self_written  %>
       <% @total = (@total+12).round(2) %> 
       
       <div class="row">
        <div class="col-md-6">
          <%= raw("Cover Song fees for #{subscription_item.itemable.album.album_name}:")%> 
        </div>
        <div class="col-md-offset-4 col-md-2">
          <%= raw("12")%> 
        </div>
       </div>
       <% end %>

       <% if subscription_item.subscription.shazam  %>
       <% @total = (@total+0.99).round(2) %> 
       <div class="row">
        <div class="col-md-6">
          <%= raw("Shazam:")%> 
        </div>
        <div class="col-md-offset-4 col-md-2">
          <%= raw("$0.99")%>
        </div>
       </div>
       <% end %>

       <% if subscription_item.subscription.youtube  %>
       <% @total = (@total+4.95).round(2) %> 

       <div class="row">
        <div class="col-md-6">
          <%= raw("YouTube Money:")%> 

        </div>
        <div class="col-md-offset-4 col-md-2">
          <%= raw("$4.95") %>  
        </div>
       </div>
       <% end %>

       <% if subscription_item.subscription.store_maximizer  %>
       <% @total = (@total+0).round(2) %> 

       <div class="row">
        <div class="col-md-6">
          <%= raw("Store Maximizer:")%> 
        </div>
        <div class="col-md-offset-4 col-md-2">
          <%= raw("FREE")%>
        </div>
       </div>
       <% end %>
      
       <% elsif subscription_item.itemable_type=='AlbumAddon' && subscription_item.itemable.album.songs.count!=1 %> <br>

       <b><%= raw("Charges for #{subscription_item.itemable.album.album_name} <br/>") %></b>
       <% subscription_item.itemable.album.songs.each do |song| %>
       <%if !song.self_written  %>
       <% @total = (@total+12).round(2) %> 
       <div class="row">
        <div class="col-md-6">
          <%= raw("Cover Song (#{song.song_title}):")%> 
        </div>
        <div class="col-md-offset-4 col-md-2">
          <%= raw("$12.00")%>
        </div>
       </div>
       <% end %>
       <% if subscription_item.subscription.shazam  %>
       <% @total = (@total+0.99).round(2) %> 
       <div class="row">
        <div class="col-md-6">
          <%= raw("Shazam (#{song.song_title}):")%> 
        </div>
        <div class="col-md-offset-4 col-md-2">
          <%= raw("$0.99")%>
        </div>
       </div>
       <% end %>
       <% end %>
       <% if subscription_item.subscription.youtube  %>
       <% @total = (@total+14.95).round(2) %> 
       <div class="row">
        <div class="col-md-6">
          <%= raw("Youtube Money:")%> 
        </div>
        <div class="col-md-offset-4 col-md-2">
          <%= raw("$14.95")%>
        </div>
       </div>
       <% end %>
       <% if subscription_item.subscription.store_maximizer  %>
       <% @total = (@total+0).round(2) %> 
       <%# <% @total = (@total+7.95).round(2) %> 
       <div class="row">
        <div class="col-md-6">
          <%= raw("Store Maximizer:")%> 
        </div>
        <div class="col-md-offset-4 col-md-2">
          <%# <%= raw("$7.95")%>
          <%= raw("FREE")%>
        </div>
       </div> 
       <% end %>
       <% end %>
       <% end %>
       <% end %>
      
       <br/>
       <b> 
       <div class="row">
        <div class="col-md-6">
          <%= raw("Total Annual Fee")%> 
        </div>
        <div class="col-md-offset-4 col-md-2">
          $<%= @total %> 
        </div>
       </div> 
       </b><br>

       <%=link_to "Click to Remove Shazam & iPhone Siri", subscription_path(current_subscription_order), data: { params: { subscription: { shazam: false, youtube: current_subscription_order.youtube, store_maximizer: current_subscription_order.store_maximizer, total: current_subscription_order.total } }.to_param }, :method => 'PATCH', remote: true if current_subscription_order.shazam %>
       <br/>
       <%=link_to "Click to Remove YouTube Money", subscription_path(current_subscription_order), data: { params: { subscription: { shazam: current_subscription_order.shazam, youtube: false, store_maximizer: current_subscription_order.store_maximizer, total: current_subscription_order.total } }.to_param }, :method => 'PATCH', remote: true if current_subscription_order.youtube %>
       <br/>
       <%=link_to "Click to Remove Store Maximizer", subscription_path(current_subscription_order), data: { params: { subscription: { shazam: current_subscription_order.shazam, youtube: current_subscription_order.youtube, store_maximizer: false, total: current_subscription_order.total } }.to_param }, :method => 'PATCH', remote: true if current_subscription_order.store_maximizer %>
       <br><br><br>
    </div><!-- end total-show-display -->


   <br>
   <%= link_to "Make Payment", transaction_logs_path( transaction_logs: { amount: @total} ), :class => 'btn btn-lg solid-button', :method => 'POST', data: {confirm: 'Please verify the total in the form. This is an annual fee to be paid for the extra features selected for these albums. We will collect the balance in one month. Please click on OK to confirm.'} %><br/>
  
    <% if current_user.transaction_logs.empty? %> <br>
      <%= raw("*Artists pay this annual fee for unlimited album uploads. Extra features, however, will cost more")%> 
    <% else %>
    <% end %>

 </div> <!-- ends total_show -->
</div> <!-- ends payment_page id -->

app/views/static_pages/dashboard.html.erb
<%= render "songs/secondheader" %>
<div class="row">
  <div class="col-sm-offset-1 col-sm-10 li-styling">
<% if !@albums.nil? %>

<% @albums.each do |album| %>
  <li class="album_<%= album.id %>">
    <span class="album_index_name"> <h3><%=album.album_name %></h3> </span>
    <span class="album_link"> <%= link_to "Details", album_path(album) %></span>
    <span class="album_edit"> <%= link_to "Edit", edit_album_path(album) %></span>
  </li>
  <% album.songs.each do |song| %>
    <li class="song_<%= song.id %>">
      <span class="song_index_name"> <%=song.song_title %> </span>
      <span class="song_link"> <%= link_to "Details", song_path(song) %></span>
      <span class="song_edit"> <%= link_to "Edit", edit_song_path(song) %></span>
    </li>
  <% end %>
<% end %>
<% else %>
  <%= raw("You have not yet uploaded any songs or albums") %>
<% end %>
  </div>
</div>

app/views/static_pages/home.mobile.erb
<!DOCTYPE html>
<html>
<head>
<title>Alphabeats - Invest in music</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<link href='https://fonts.googleapis.com/css?family=Lato:400,700,700italic' rel='stylesheet' type='text/css'>
<%= csrf_meta_tags %>
<%= favicon_link_tag 'favicon.ico' %>

</head>

<div class="container-fluid">

<div class="row" id="mobile-home">
  <div id="mobile-cover"> <br><br>
  <h1>Alphabeats: <br> Invest in Music</h1> <br>
  <p>To sign up, access the website using a laptop or desktop</p> <br><br>
  <div class="col-xs-3"></div>
  <a target="_blank" href="https://youtu.be/XzCaicoFb1U"><%= image_tag("play.png", class: "img-responsive") %></a>
  </div><!-- ends #cover -->
  <div id="mobile-welcome-text">
  <h1>A Crowdsourced Record Label</h1>
  <p>Invite the music industry's bloggers and influencers to <b>invest in your songs</b>. Then, let them promote your music while you continue performing live and producing new tracks.</p>
  </div><!-- ends #welcome-text -->
  <div id="mobile-steps">
    <p>1. Upload: Artists upload songs on Alphabeats. We will then put them on all the major streaming services.</p>
    <p>2. Invest: Using the Alphabeats stock-market like platform, influencers can invest in their favorite songs.</p>
    <p>3. Share: With personal interest in the song's success, investors endorse the track with their followers.</p>
  </div>

  <div class="row">
    <div class="fbcenter">
    <a href="https://www.facebook.com/alphabeatsmusic"><i class="fa fa-facebook fblogo"></i></a> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
    <a href="https://www.instagram.com/alphabeats_music/"><i class="fa fa-instagram iglogo"></i></a> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
    <a href="mailto:s+email@alphabeatsmusic.com"><i class="fa fa-envelope-o gmlogo"></i></a>
    <br/><br/>
    </div>
  </div> <!-- ends icon-text-links -->
</div><!-- ends #home -->
</div><!-- ends container-fluid -->
</html>

app/views/static_pages/letter.html.erb
<div class="row">
<div class="col-md-offset-1 col-md-10">
  <h2 class="centre">About Us</h2>
<h2>Me</h2>
<p>
  Hello. My name is Shenil, and I am the founder of Alphabeats. We aim to help uncover the many talented artists living amongst us and help them become popular. In our case, we focus on musicians.
</p>

<h2>What</h2>
<p>
<b>
  Alphabeats allows independent musicians to raise money against the earnings of a song's digital income. The digital income includes proceeds from popular streaming channels such as Spotify, Apple Music, Tidal and Deezer.
</b>  
</p>

<p>
  "Equity crowdfunding" is the technical term used to describe this business model. I like to think of Alphabeats as a crowdsourced record label with no strings attached. By this, I'm referring to the fact that artists raise money on a per song basis, which has the following implications for the artist and the potential investors:
</p>

<table>
<tr>
  <th>Artist</th>
  <th>Potential Investors</th>
</tr>
<tr>
  <td>1. Artists do not have to put all of their songs on the platform, or share income of newer songs with investors</td>
  <td>1. Investors do not need to rely on the artist producing new work, nor does the quality of other work have a direct impact on that particular song's performance.</td>   
</tr>
<tr>
  <td>2. The funding request will be of smaller amounts, allowing most fans to take part in investing</td>
  <td>2. Investors' benefits are tied only to the song that they invest in, making it easier to decide the value of their investment.</td>
</tr>
<tr>
  <td>3. Artists do not have a long term commitment with their investors</td>
  <td>3. The cost of investing is much lower, making the experience more about discovering great music instead of a worrysome.</td>
</tr>
</table>
<br>

<h2>Who</h2>
<p>
  If you are a musician, here are some ways you can use Alphabeats to advance in the industry. Firstly, you can use Alphabeats to gain traction for your work to increase your chances of signing with a major record label eventually. Alternatively, you can use Alphabeats to become popular and stay independent. We are currently offering one year free subscription for all Irish artists and bands.
</p>
<p>
  On the other end, investing may be of interest if you are a music connoisseur, an aspiring record label executive, or a finance savy person looking for something unique. Whichever category you fit into, what compares to making money using your favorite streaming service and social media platforms?
</p>

<h2>How</h2>
<p>
Now that I've touched upon what our aim and idea is, and why I'm doing this, here are the steps of the business model so you can understand how it works:
</p>
<p>
Step 1: The musician submits a song through Alphabeats. We put the song on major streaming services through our partner aggregator, <a href="https://distrokid.com">DistroKid</a>. Once the song is approved and uploaded, the artist can make an investment request, asking for money in return for a portion of the song's earnings.
</p>
<p>
Step 2: Fans of the song can invest in it, giving them a claim of the song's income. This motivates them to share the song to others (from their preferred streaming service). As more people download or stream the song, the artist and the song's investors will receive higher payouts and the song will climb ranks in the well known streaming platforms. 
</p>
<p>
Step 3: Soon the song's payouts will exceed the amount the investor gave, giving them an income opportunity. Alternatively, the investor can sell their claim of income of the song to other investors on the Alphabeats marketplace. More importantly, the song will be exposed to a wider audience in the process, and create more fans for the future! 
</p>

<h2>You</h2>
<p>
I look forward to your questions, feedback, or "Hello" messages.
</p>

<br>

</div><!-- end of col-md -->

</div><!-- end of row -->


<div class="row">
  <div class="col-sm-6">
      <a href="<%= updates_path %>">
  <div class="signup-updates">
    <button class="btn btn-lg btn-transparent">
      <span id="updates">Sign up for updates</span>
    </button>
    </div>
    </a>
      </div>
      <div class="col-sm-6">
          <a href="<%= contact_path %>">
      <div class="signup-updates">
    <button class="btn btn-lg btn-transparent">
      <span id="updates">Contact us</span>
    </button>
    </div>
    </a>
  </div>
</div>

app/views/static_pages/membership.html.erb
<%= render "songs/secondheader" %>
  <br>
  <br>
  <br>
<div class="container">
  <div class="row">
    <% if !current_user.musician? %>
    <h2>Become a musician on Alphabeats</h2>
    <p>Becoming a musician costs only 20USD an year.As a musician on alphabeatsmusic you can upload your songs to multiple music stores at once. Apart from that you can sell shares of your songs on the alphabeats share market. </p>
    <h3> Your current balance is: <%= current_user.wallet.nil? ? 0 : current_user.reload.wallet.amount %> &nbsp;&nbsp; </h3>
    <p>Membership is autorenewed subject to availability of balance in wallet</p>
    <br/><br/><br/><br/>
    <div class="col-md-offset-5">
      <a href="<%= memberships_path %>" data-method="post">
        <div class="signup-updates">
          <button class="btn btn-lg btn-transparent solid-button">
            <span id="updates">Activate Membership</span>
          </button>
        </div>
      </a>

    </div>
    <% end %>
  </div>
</div>

app/views/static_pages/open_trades.html.erb
<div class="<%= Width::CONTAINER %>">
<div class="row">
  <div class="col-md-6">
    <h2 class="center-text" >My Open Bids</h2>
  
    <table class="table ">
      <thead>
        <tr>
          <th></th>
          <th>Song</th>
          <th>Bid Status</th>
          <th>Bid Share</th>
          <th>Bid amount</th>
          <th>Bid Price</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
     <tbody class="song-table">
       <%= render @bids %>
     </tbody>
   </table>
  </div>
  <div class="col-md-6">
    <h2 class="center-text" >My Open Offers</h2>
    <table class="table ">
      <thead>
        <tr>
          <th></th>
          <th>Song</th>
          <th>Offer Status</th>
          <th>Offer Share</th>
          <th>Offer amount</th>
          <th>Offer price</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
     <tbody class="song-table">
       <%= render @offers %>
     </tbody>
   </table>
  
  </div>
</div>
</div>

app/views/static_pages/payment_page.html.erb
<%= render "songs/secondheader" %>
<div class="row">
<div class=" col-sm-offset-1 col-sm-10">
  <h2 class="center-text">Payment Page</h2> <br>
  <div class="col-md-3 extra-features">
    <a href="<%= subscription_path(current_subscription_order) %>", data-remote="true" data-params="subscription%5Bshazam%5D=true" data-method="PATCH" rel="nofollow">
    <div class="signup-updates">
      <button class="btn btn-lg solid-button">
        <span id="updates">Add Shazam & iPhone Siri</span>
      </button>
    </div> 
  </a>
  <%=link_to "Track: $0.99 per year", subscription_path(current_subscription_order), data: { params: { subscription: {  shazam: true} }.to_param }, :method => 'PATCH', remote: true%> <br><br>
  <br><p class="feature-description">Make it easy for people to identify this single if they hear it playing on radio/tv, in stores, restaurants, parties, etc.</p>
  <br/>
  </div> 
  <div class="col-md-5 extra-features">
    <div class="row"></div>
    <a href="<%= subscription_path(current_subscription_order) %>", data-remote="true" data-params="subscription%5Byoutube%5D=true" data-method="PATCH" rel="nofollow">
    <div class="signup-updates">
      <button class="btn btn-lg solid-button">
        <span id="updates">Add Youtube Money</span>
      </button>
    </div>
  </a> 
   <%=link_to "Track: $4.95/year + 20% of YouTube ad revenue", subscription_path(current_subscription_order), data: { params: { subscription: {  youtube: true} }.to_param }, :method => 'PATCH', remote: true%> <br>
   <%=link_to "Album: $14.95/year + 20% of YouTube ad revenue", subscription_path(current_subscription_order), data: { params: { subscription: {  youtube: true} }.to_param }, :method => 'PATCH', remote: true%><br><br>
   <p class="feature-description">Get notified & paid if your music is ever used in any YouTube videos. We'll add this single/ album to YouTube's Content ID database, and continually scan for matches. When your music is detected in any YouTube video, you'll be notified—and ad revenue will automatically go to you.</p>
<br/>
  </div>
  <div class="col-md-3 extra-features">
    <a href="<%=subscription_path(current_subscription_order) %>", data-remote="true" data-params="subscription%5Bstore_maximizer%5D=true" data-method="PATCH" rel="nofollow">
      <div class="signup-updates">
        <button class="btn btn-lg solid-button">
          <span id="updates">Add Store Maximizer</span>
        </button>
      </div>
    </a>

 <%=link_to "FREE", subscription_path(current_subscription_order), data: { params: { subscription: {  store_maximizer: true} }.to_param }, :method => 'PATCH', remote: true%> <br><br>
 <br><p class="feature-description">Alphabeats will automatically deliver this album to new stores and streaming services as we add them. Which is often. We'll give you notice before adding.</p>

</div>

  </div>
</div>
<br>
    
<div class="row">
<%= render "total_show" %>
</div>

app/views/static_pages/shortlist.html.erb
    <div class="modal fade" id="low_balance_bid" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <br/>
        </div>
        <div class="modal-body">

        <div class="field">
          <p style="color:red;" >You do not have sufficient balance in your wallet to make the bid</p>
        </div>

        </div>
        <div class="modal-footer">
          <button type="button" id="low_balance_bid" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= link_to "Add money", wallet_path,  class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    </div>

<div class="<%= Width::CONTAINER %>">
    <table class="table ">
      <thead>
        <tr>
          <th></th>
          <th>Song</th>
          <th>Make Bid</th>
        </tr>
      </thead>
     <tbody class="song-table">
      <% @songs.each do |song| %>
      <tr>
        <td>
            <%= render partial: "shared/song_dropdown", locals: {song: song} %>
        </td>
        <td><%=song.song_title %></td>
        <td>
          <%= form_tag bids_path, method: :post, remote: true, :class => "form-inline", :id => "song_#{song.id}" do %>
              <%= label_tag(:share, "%") %>
             <%= text_field_tag :share,"", class: "input input-style" %>
              <%= label_tag(:amount, "$") %>
             <%= text_field_tag :amount,"", class: "input input-style" %>
             <%= hidden_field_tag "song_id", song.id %>
             <%= submit_tag "Submit", name: nil, class: "btn btn-transparent" %>   
          <% end %> 
        </td>
      </tr>
      <% end %>
     </tbody>
   </table>
</div>

app/views/static_pages/wallet.html.erb
  <div class="container">
    <div class="row">
      <h3> Balance: <%= current_user.wallet.nil? ? 0 : current_user.reload.wallet.amount %> &nbsp;&nbsp;
       <% if current_user.transaction_logs.where(transaction_type:TransactionLog::TransactionType::WITHDRAWL_FROM_WALLET) %>
        <p>Pending  Withdrawl: <%= current_user.transaction_logs.where(transaction_type:TransactionLog::TransactionType::WITHDRAWL_FROM_WALLET, transaction_status:TransactionLog::TransactionStatus::PENDING).collect {|t| t.amount }.sum %></p>
       <% end %>
      </h3>
      <div class="col-md-6">
      <p>
         <!-- <br/><br/> -->
         <h3>Add money</h3>
      <%= form_tag express_checkout_path do %>
          <%= label_tag(:amount, "Add Money  ") %>
         <%= text_field_tag :amount,"In dollars", class: "input input-style" %>
         <br/><br/>
         <%= image_submit_tag("https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif") %>   
      <% end %> 
      </p>
      </div>
      <div class="col-md-6">
      <p>
         <!-- <br/><br/> -->
         <h3>Withdraw money</h3>
      <%= form_tag confirm_withdrawl_path do %>
        <%= label_tag(:amount, "Money") %>
         <%= text_field_tag :amount,"In dollars", class: "input input-style" %>
         <br/><br/>
          <%= label_tag(:paypal_id, "Paypal Id  ") %>
         <%= text_field_tag :paypal_id,"paypal email address", class: "input input-style" %>
         <br/><br/>
    <%# <%= f.button :submit, class: 'btn btn-transparent btn-lg solid-button' %>
    <%= submit_tag "Continue",  class: 'btn btn-transparent btn-lg solid-button' %>
      <% end %> 
      </p>
      </div>


    </div>
  </div>