config/routes.rb
Rails.application.routes.draw do
  

  resources :memberships, only: [:create]
  resources :shortlists, only: [:create, :destroy, :index]

  resources :song_stats do
      collection { post :import }
  end

  resources :transaction_logs
  resources :subscriptions, only: [:update, :destroy]
  resources :subscription_items, only: [:create, :update, :destroy]

  resources :songs do
    collection { get :all_index }
  end

  resources :albums

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
  resources :users, only: [:show, :update, :edit]

  get 'static_pages/home'
  get 'after_signup_home', to: "static_pages#after_signup_home"
  get 'inactive_signup_home', to: "static_pages#inactive_signup_home"
  get 'about', to: "static_pages#about"
  get 'faq', to: "static_pages#faq"
  get 'contact', to: "static_pages#contact"
  get 'updates', to: "static_pages#updates"
  get 'letter', to: "static_pages#letter"
  get 'pricing', to: "static_pages#pricing"
  get 'dashboard', to: "static_pages#dashboard"
  get 'terms', to: "static_pages#terms"
  get 'cart_page', to: "static_pages#cart_page"
  get 'payment_page', to: "static_pages#payment_page"
  get 'post_login_home', to: "static_pages#post_login_home"
  get 'discover', to: "static_pages#discover"
  get 'performance', to: "static_pages#performance"
  get 'wallet', to: "static_pages#wallet"
  get 'holdings', to: "static_pages#holdings"
  get 'opentrades', to: "static_pages#open_trades"

  get 'membership', to: "static_pages#membership"
  get 'renewals', to: "static_pages#renewals"

  resources :bids, only: [:create, :update, :destroy]
  resources :offers, only: [:create, :update, :destroy]

  root 'static_pages#home'
  get 'albums/:id/album_song' => 'albums#album_song_show', as: :album_song

  resources :payments, only: [:new, :create]
  post 'express_checkout' => 'payments#express_checkout', as: :express_checkout
  post 'confirm_withdrawl' => 'payments#confirm_withdrawl', as: :confirm_withdrawl
  get 'initiate_withdrawl_email_verification' => 'payments#initiate_withdrawl_email_verification', as: :initiate_withdrawl_email_verification

end

app/models/shortlist.rb
# == Schema Information
#
# Table name: shortlists
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  song_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Shortlist < ActiveRecord::Base
  
  belongs_to :song
  belongs_to :user

  validates_presence_of :user_id, :song_id
end

app/controllers/shortlists_controller.rb
class ShortlistsController < ApplicationController

  before_action :authenticate_user!

  # def discover
  #   @songs = Song.all - current_user.shortlist_songs
  # end

  def index
    @songs = current_user.shortlist_songs
    @bids = current_user.bids.order(updated_at: :desc)
  end

  def create
    if !current_user.shortlists.find_by(song_id: params[:song_id])
      @shortlist = current_user.shortlists.new(song_id: params[:song_id])
      @shortlist.save
    else
      render nothing: true
    end
  end

  def destroy
    @shortlist = current_user.shortlists.find_by(song_id: params[:id])
    if @shortlist
      @shortlist.destroy
    else
      render nothing: true
    end
  end

end

app/helpers/shortlists_helper.rb
module ShortlistsHelper
end

app/views/shortlists/create.js.erb
$("#song_<%= @shortlist.song.id %>").fadeOut(500, function(){
	$(this).remove();
});

app/views/shortlists/destroy.js.erb
$("#shortlist_song_<%= @shortlist.song.id %>").fadeOut(500, function(){
	$(this).remove();
});

app/views/shortlists/index.html.erb
    <div class="modal fade" id="low_balance_bid" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <br/>
        </div>
        <div class="modal-body">

        <div class="field">
          <p style="color:red;" >You do not have sufficient balance in your wallet to make the bid</p>
        </div>

        </div>
        <div class="modal-footer">
          <button type="button" id="low_balance_bid" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= link_to "Add money", wallet_path,  class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    </div>

<div class="<%= Width::CONTAINER %>">
  <h2>Shortlisted songs</h2>
    <table class="table ">
      <thead>
        <tr>
          <th></th>
          <th>Song</th>
          <th>Artist</th>
          <th>Release Date</th>
          <th>Income till Date</th>
          <th>Last trade price(per %)</th>
          <th>Make Bid</th>
          <th></th>
        </tr>
      </thead>
     <tbody class="song-table">
      <% @songs.each do |song| %>
      <tr id="shortlist_song_<%= song.id %>">
        <td>
            <%= render partial: "shared/song_dropdown", locals: {song: song} %>
        </td>
        <td><%=song.song_title %></td>
        <td><%=song.musician.name %></td>
        <td><%=song.album.get_release_date %></td>
        <td><%=song.income_till_date %></td>
        <td><%=song.last_trade_price %></td>
        <td>
          <%= form_tag bids_path, method: :post, remote: true, :class => "form-inline input-mini", :id => "song_#{song.id}" do %>
              <%= label_tag(:share, "%") %>
             <%= text_field_tag :share,"", class: "input input-style input-5em-width" %>
              <%= label_tag(:amount, "$") %>
             <%= text_field_tag :amount,"", class: "input input-style input-5em-width" %>
             <%= hidden_field_tag "song_id", song.id %>
             <%= submit_tag "Submit", name: nil, class: "btn btn-sm btn-transparent" %>   
          <% end %> 
        </td>
        <td><%= link_to "x", shortlist_path(song.id), method: :delete, remote: :true, :data => {:confirm => 'Are you sure you want to remove this song from shortlist?'} %><td/>
      </tr>
      <% end %>
     </tbody>
   </table>

   <br/><br/>

  <h2>My Open Bids</h2>
    <table class="table ">
      <thead>
        <tr>
          <th></th>
          <th>Song</th>
          <th>Artist</th>
          <th>Release Date</th>
          <th>Income till Date</th>
          <th>Last trade price(per %)</th>
          <th>Bid Share</th>
          <th>Bid amount</th>
          <th>Bid price(per %)</th>
          <th></th>
        </tr>
      </thead>
     <tbody class="song-table" id="open-bid-table">
      <%= render @bids  %>
     </tbody>
   </table>
</div>