config/routes.rb
Rails.application.routes.draw do
  

  resources :memberships, only: [:create]
  resources :shortlists, only: [:create, :destroy, :index]

  resources :song_stats do
      collection { post :import }
  end

  resources :transaction_logs
  resources :subscriptions, only: [:update, :destroy]
  resources :subscription_items, only: [:create, :update, :destroy]

  resources :songs do
    collection { get :all_index }
  end

  resources :albums

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
  resources :users, only: [:show, :update, :edit]

  get 'static_pages/home'
  get 'after_signup_home', to: "static_pages#after_signup_home"
  get 'inactive_signup_home', to: "static_pages#inactive_signup_home"
  get 'about', to: "static_pages#about"
  get 'faq', to: "static_pages#faq"
  get 'contact', to: "static_pages#contact"
  get 'updates', to: "static_pages#updates"
  get 'letter', to: "static_pages#letter"
  get 'pricing', to: "static_pages#pricing"
  get 'dashboard', to: "static_pages#dashboard"
  get 'terms', to: "static_pages#terms"
  get 'cart_page', to: "static_pages#cart_page"
  get 'payment_page', to: "static_pages#payment_page"
  get 'post_login_home', to: "static_pages#post_login_home"
  get 'discover', to: "static_pages#discover"
  get 'performance', to: "static_pages#performance"
  get 'wallet', to: "static_pages#wallet"
  get 'holdings', to: "static_pages#holdings"
  get 'opentrades', to: "static_pages#open_trades"

  get 'membership', to: "static_pages#membership"
  get 'renewals', to: "static_pages#renewals"

  resources :bids, only: [:create, :update, :destroy]
  resources :offers, only: [:create, :update, :destroy]

  root 'static_pages#home'
  get 'albums/:id/album_song' => 'albums#album_song_show', as: :album_song

  resources :payments, only: [:new, :create]
  post 'express_checkout' => 'payments#express_checkout', as: :express_checkout
  post 'confirm_withdrawl' => 'payments#confirm_withdrawl', as: :confirm_withdrawl
  get 'initiate_withdrawl_email_verification' => 'payments#initiate_withdrawl_email_verification', as: :initiate_withdrawl_email_verification

end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id                  :integer          not null, primary key
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  song_title          :string
#  lyrics              :text
#  terms               :boolean
#  audio_file          :string
#  duration            :time
#  note_to_admin       :text
#  album_id            :integer
#  user_id             :integer
#  explicit_lyrics     :boolean
#  self_written        :boolean
#  original_artist     :string
#  original_song_title :string
#  spotify             :string
#  itunes              :string
#  apple_music         :string
#  google_play         :string
#  amazon              :string
#  r_dio               :string
#  deezer              :string
#  tidal               :string
#  youtube             :string
#  microsoft_groove    :string
#  media_net           :string
#  producer            :string
#  producer_email      :string
#  view_count          :integer
#  download_count      :integer
#  income_till_date    :decimal(7, 2)
#

class Song < ActiveRecord::Base


  belongs_to :musician, class_name: User.name, foreign_key: 'user_id'
  belongs_to :album
  has_many :song_stats


  validates_presence_of :song_title,  :terms, :audio_file, :album_id, :user_id 
 # validates_presence_of :song_title,  :terms, :audio_file, :album_id, :user_id,  :original_artist, :original_song_title

  validates :terms, acceptance: {accept: true}
  validates_inclusion_of :explicit_lyrics, :in => [true, false]
  validates_inclusion_of :self_written, :in => [true, false]
  validates :producer_email, :allow_blank => true, format: {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})|^$\z/i, :message => "must be in a valid email format"}
  validates :income_till_date, :allow_blank => true, numericality: true
  validates :view_count, :allow_blank => true, numericality: { :only_integer => true }
  validates :download_count, :allow_blank => true, numericality: { :only_integer => true} 

  #trading module
  has_many :shareholders
  has_many :shareholder_users, through: :shareholders, class_name: 'User'

  has_many :bids
  has_many :bid_users, through: :bids, class_name: 'User'

  has_many :offers
  has_many :offer_users, through: :offers, class_name: 'User'

  has_many :trade_logs
  
  #shortlist module
  has_many :shortlists
  has_many :shortlist_users, through: :shortlists, source: :user

  mount_uploader :audio_file, AudioFileUploader

  # extend ConvertCsv
  #
  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |song_stat_row|
        csv << song_stat_row.attributes.values_at(*column_names)
      end
    end
  end

  def song_fully_owned?
    return true if self.shareholders.count == 1 || self.shareholders.find_by(user_id: self.musician.id).share == 100
    return false
  end

  def last_trade_price
      trade_logs.present? ? trade_logs.last.trade_price : ""
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :authorize_musician, except: :show

  
  load_and_authorize_resource :only => [:show,:edit,:update]

  def all_index
    if current_user.admin?
      @all_songs = Song.all
      respond_to do |format|
        format.csv { send_data @all_songs.to_csv }
      end
    else
      redirect_to root_url, :alert => "You are not authorized to access"
    end
  end

  def index
    @songs = current_user.songs
  end

  def new
    @song = current_user.songs.new
    @song_album_list = song_album_list #Defined in application controller
  end
  
  def create
    @song = current_user.songs.new(song_params)
    if @song.save
      redirect_to album_song_path(@song.album.id), notice: "The song #{@song.song_title} has been created"
    else
      @song_album_list = song_album_list #Defined in application controller 
      # and makes sure album field is prepopulated properly when there is an error in the form
      render :action => "new"
    end
  end

  def show
    # if user_signed_in?
    #   @song = current_user.songs.find(params[:id])
    # else
      @song = Song.find(params[:id])
    # end
  end

  def edit
    @song = current_user.songs.find(params[:id])
    # @song = current_user.song.find(params[:id])
  end

  def update
    @song = current_user.songs.find(params[:id])
    # @song = current_user.song.find(params[:id])
    if @song.update_attributes(song_params)
      redirect_to song_path(@song), notice: "The song #{@song.song_title} has been updated"
    else
      render "edit"
    end
  end

  def destroy
    @song = current_user.songs.find(params[:id])
    @song.destroy
    redirect_to album_song_path(@song.album), notice: "The song #{@song.song_title} has been deleted"
  end

private
  def song_params
    params.require(:song).permit(:song_title, :song_writer, :lyrics, :terms, :audio_file,  :duration, :note_to_admin, :album_id, :explicit_lyrics, :self_written, :original_artist, :original_song_title, :spotify, :itunes, :apple_music, :google_play, :amazon, :r_dio, :deezer, :tidal, :youtube, :microsoft_groove, :media_net, :producer, :producer_email,:view_count, :download_count, :income_till_date)
  end

end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<div class="col-md-12 bg-album-song-color"><br>
  <!-- <div class="form&#45;bg"> -->
  <%= simple_form_for song, :html => { class: 'song-form-style' } do |f| %>
    <div class="row">
      <%= render partial: 'shared/error_messages', locals: {resource: song}  %>

      <div class="row">
            <div class="col-md-offset-1 col-md-2">Album</div>
            <div class="col-md-7"><%= f.input :album_id, label: '', input_html: {class: 'input input-style form-control'}, collection: @song_album_list, label_method: :text, value_method: :code, include_blank: "Select or Create an Album" %>
              <ul class="form-sidenote">If you are uploading a single, you must still create a unique album for it. We suggest you use the name of the single itself as the album name.</ul>
            </div>
      </div>
      <br><br>

      <div class="row">
            <div class="col-md-offset-1 col-md-2">Song title</div>
            <div class="col-md-7"><%= f.input :song_title, label: '', input_html: {class: 'input input-style form-control'} %>
              <ul class="form-sidenote">Featured artists: Use the word feat. in parenthesis, with names separated by ampersand &amp; commas. Example: Sweetest Girl (feat. Akon, Lil Wayne &amp; Niia)</ul>
              <ul class="form-sidenote">Instrumental/remix/versioning: If the title needs an explanatory word, put it in parenthesis. Example: Cheerleader (instrumental)</ul>
              <ul class="form-sidenote">Multiple parenthesis: Titles can only have 1 set of parenthesis. If you need more, use brackets instead. Example: C'mon (Catch 'Em by Surprise) [Tiësto remix] [feat. Busta Rhymes]</ul>
              <ul class="form-sidenote">Cover songs: If a cover, remix, or mashup, do not include the original artist's name here. Example: Thriller</ul>   
              <ul class="form-sidenote">Capitalization: Use title case. Stores will reject all-lowercase or wEirD capitalization. Example: It's the End of the World As We Know It (And I Feel Fine)</ul>
            </div>
      </div>
      <br><br>

      <div class="row">
            <div class="col-md-offset-1 col-md-2">*Explicit Lyrics</div>
            <div class="col-md-7"><%= f.collection_radio_buttons :explicit_lyrics, [[true, 'Yes'] ,[false, 'No']], :first, :last , :item_wrapper_class => "radio-css"%>
            </div>
      </div>
      <br><br>

      <div class="row">
            <div class="col-md-offset-1 col-md-2">Duration (mm:ss)</div>
            <div class="col-md-7"><%= f.input :duration, label: '.', input_html: {class: 'input input-style form-control', autocomplete:'off'}, :default=> Time.parse("00:00") %>
            </div>
      </div>
      <br><br>

      <div class="row">
            <div class="col-md-offset-1 col-md-2">Upload Audio File</div>
            <div class="col-md-7"><%= f.input :audio_file, label: '', input_html: {class: 'input input-style form-control'} %> 
              <ul class="form-sidenote">WAV, WMA, M4A, FLAC, MP3, or CDDA</ul>
            </div>
      </div>
      <br><br>

      <div class="row">
            <div class="col-md-offset-1 col-md-2">Lyrics</div>
            <div class="col-md-7"><%= f.input :lyrics, label: '.', input_html: {class: 'input input-style form-control'} %>
            </div>
      </div>
      <br><br>

      <div class="row">
            <div class="col-md-offset-1 col-md-2">Song Writer</div>
            <div class="col-md-7"><%= f.collection_radio_buttons :self_written, [[true, "I wrote this song (it's an original tune)"] ,[false, "Another artist wrote it (it's a cover, read below for more info)"]], :first, :last , :item_wrapper_class => "radio-css", :id => "self_written_check" %>
              <div id="cover_song" style="display:none;">
                <ul class="cover-song-sidenote"><b>Cover songs are okay!</b><br>A "cover song" is a song that you performed &amp; recorded yourself, but the music was written by someone else. For example, when your band plays "Smooth Criminal" (written by Michael Jackson). This is totally okay—DistroKid makes it easy and legal to sell cover songs.</ul><br>
                <ul class="cover-song-sidenote"><b>Sampling is probably not okay</b><br>Sampling is when you use the actual recording of another artist's performance. For example, if you use the 1971 recording of Led Zeppelin's "When The Levee Breaks" as your drum track. That's generally not allowed, unless you have permission from the original artist.</ul><br>
                <ul class="cover-song-sidenote"><b>DistroKid will handle licensing &amp; pay the original songwriter(s)</b><br>DistroKid will obtain the required compulsory mechanical license for you. We'll automatically deduct the legally-mandated fee of 9.1¢ per song sold in the U.S. from your earnings and pay it to the original songwriter. You'll get 100% of the rest.</ul><br>
                <ul class="cover-song-sidenote"><b>Fee: DistroKid charges a fee of $1 per month (paid annually, so $12 billed to your cc) to manage this cover song for you. They will:</b></ul>
                <ul class="cover-song-sidenote">Obtain license(s)</ul>
                <ul class="cover-song-sidenote">Pay the original songwriter(s) every month</ul>
                <ul class="cover-song-sidenote">Keep up-to-date on copyright laws affecting your music</ul>
                <ul class="cover-song-sidenote">Do the things described <u><a href="http://www.copyright.gov/licensing/sec_115.html">here</a></u> and <u><a href="http://www.copyright.gov/title17/92chap1.html#115">here</a></u></ul>
                <br>
                <div class="row">
                  <div class="col-md-3">Original Songwriter</div>
                <div class="col-md-9"><%= f.input :original_artist, label: '', input_html: {class: 'input input-style form-control'} %></div>
                </div>
                <br>
                <div class="row">
                  <div class="col-md-3">Original Song Title</div>
                <div class="col-md-9"><%= f.input :original_song_title, label: '', input_html: {class: 'input input-style form-control'} %></div>
                </div>
              </div>
              
            </div>
      </div>
      <br><br>

      <div class="row">
            <div class="col-md-offset-1 col-md-2">Producer</div>
            <div class="col-md-7"><%= f.input :producer, label: '.', input_html: {class: 'input input-style form-control'} %>
            </div>
      </div>
      <br><br>

      <div class="row">
            <div class="col-md-offset-1 col-md-2">Producer Email</div>
            <div class="col-md-7"><%= f.input :producer_email, label: '.', input_html: {class: 'input input-style form-control'} %>
            </div>
      </div>
      <br><br>



      <div class="row">
            <div class="col-md-offset-1 col-md-2">Note to Admin</div>
            <div class="col-md-7"><%= f.input :note_to_admin, label: '.', input_html: {class: 'input input-style form-control'} %>
              <ul class="form-sidenote">If the song's royalties are being shared amongst multiple people, please provide their email address and percent of rights owned, and separate individuals by commas. Example songwriter@alphabeatsmusic.com (50%), drummer@example.com (10%)</ul>
              <ul class="form-sidenote">If you would like to delete a single, please write a note here</ul> 
              <ul class="form-sidenote">Special requests?</ul>
            </div>
      </div>

    </div>


    <%= render partial: "shared/service_url_edit", locals: {f: f} %>

    <% if current_user.admin? %>
      <%= f.input :view_count, label: 'View Count', input_html: {class: 'input input-style form-control'} %> <br><br>
      <%= f.input :download_count, label: 'Download Count', input_html: {class: 'input input-style form-control'} %> <br><br>
      <%= f.input :income_till_date, label: 'Income so far on this song', input_html: {class: 'input input-style form-control'} %> <br><br>
    <% end %>
    <br><br>
    <div class="row">
      <div class="col-md-offset-4 col-md-7">
        <%= f.label :terms do %>
        <%= f.check_box :terms, :style => "float:left;" %>
        <%= f.label :terms, "&nbsp;&nbsp;" "#{link_to 'I accept these terms of service', terms_path, :target => "_blank", :class => "terms-line"}.".html_safe, :style => "float:right;" %>
      <% end %>
      </div>
      </div>

      
      <!-- <div class="col&#45;sm&#45;3"> -->
      <!--   <br/> -->
      <!-- </div> -->
    <!-- </div> -->
    <div class="col-md-offset-5"><%= f.button :submit, class: 'btn btn-transparent btn-lg solid-button' %></div>
    <% end %>
  </div>

  <script>
  $("#song_album_id").on('change', function(e) {
    var valueSelected = this.value;
    if (valueSelected == -1) {
      window.location.href=("<%= ENV['CREATE_NEW_ALBUM'] %>")
   }; 
 })
  </script>
</div>

app/views/songs/_secondheader.html.erb
<!-- <nav class="second-menu">
  <ul class="list-inline pull-right"> -->
    <% if user_signed_in? %>
    <%= raw("<nav class='second-menu'> <ul class='list-inline pull-right'>") %>
      <li><%= link_to "Create Album", new_album_path, :class =>"second-menu-font" %></li>
      <li><%= link_to "Upload Song", new_song_path, :class =>"second-menu-font" %></li>
      <li><%= link_to "Cart", cart_page_path, :class =>"second-menu-font" %></li>
      <li><%= link_to "My Albums", albums_path, :class =>"second-menu-font" %></li>
      <!-- <li><%#= link_to "Membership", membership_path, :class =>"second&#45;menu&#45;font" %></li> -->
      <li><%= link_to "Renewals", renewals_path, :class =>"second-menu-font" %></li>
    <%= raw("</ul> </nav>") %>
    <% end %>


 <!--  </ul>
</nav> -->

app/views/songs/_song_show.html.erb
<div class="row">
  
  <div class="col-sm-offset-1 col-sm-10 album-show">
    <% if can? :create, Song %>
        <% if !paid_album?(song.album) %>
          <a data-method="delete" data-confirm="Are you sure that you want to delete this song?" href="<%= song_path(song) %>">
            <span id="updates" class="delete-item">x</span>
          </a>    
        <% end %>
      <% end %>
    <br style="line-height:1em;">
    <div class="album-show-edit">
      <% if !paid_album?(song.album) %>
        <% if can? :create, Song %>
          <%= link_to "Edit Song", edit_song_path(song) %> 
        <% end %>
      <% end %>
    </div>
   <br style="line-height:2em;">
    <div class="col-sm-5">
      <h5 class='low-opacity-font' >Song Title</h5>
      <%= song.song_title %> <br/>

      <h5 class='low-opacity-font' >Song Writer</h5>
      <% if song.self_written %>
        <%= raw("Self Written") %>
      <% else %>
        <%= raw("Original artist:") %>
        <%= song.original_artist %>
        <br/>
        <%= raw("Original song title:") %>
        <%= song.original_song_title %>
      <% end %>

       
        <br/>

      <h5 class='low-opacity-font' >Album Name</h5>
      <%= song.album.album_name %> <br/>

      <% if !song.duration.nil? && !song.duration==Time.utc(2000,01,01,00,00,00) %>
        <%= raw("<h5 class='low-opacity-font' >Song Duration</h5>") %>
        <%= song.duration.strftime("%H:%M") if !song.duration.nil? && !song.duration==Time.utc(2000,01,01,00,00,00) %> <br/>
      <% end %>

      <% if can? :create, Song %>
        <%= raw("<h5 class='low-opacity-font' >Link to Song</h5>") %>
        <%= song.audio_file %> <br/>

        <%= raw("<h5 class='low-opacity-font' >Note to Admin</h5>") %>
        <%= song.note_to_admin %> <br/>

      <% end %>

      <h5 class='low-opacity-font' >Explicit Lyrics</h5>
      <% if song.explicit_lyrics %>
        <%= raw("Yes") %>
      <% else %>
        <%= raw("No") %>
      <% end %>
      
      <% if song.producer.present? %>
        <%= raw("<h5 class='low-opacity-font' >Producer</h5>") %>
        <%= song.producer %>
      <% end %>

      <% if song.producer_email.present? %>
        <%= raw("<h5 class='low-opacity-font' >Producer Email</h5>") %>
        <%= song.producer_email %>
      <% end %>

        <br/>
        <br/>

    </div>
    <div class="col-sm-7 lyrics-show-overview">
      <h5 class='low-opacity-font' >Lyrics of the Song</h5>
      <div id="lyrics-show" class="lyrics-show">
      <%= song.lyrics %> <br/>
      </div>
    </div>
  </div><!-- end col-sm-offset-1 col-sm-10 album-show -->

      <br/><br/>

      <%= render partial: "shared/service_url_show", locals: {object: song} %>
  <div class="col-sm-offset-1 col-sm-10">
    <div class="col-sm-5">
        <% if song.view_count.present? %>
          <%= raw("<h5 class='low-opacity-font' >View Count: #{song.view_count}</h5>") %>
        <% end %>
        <% if song.download_count.present? %>
          <%= raw("<h5 class='low-opacity-font' >Download Count: #{song.download_count}</h5>") %>
        <% end %>
        <% if song.income_till_date.present? %>
          <%= raw("<h5 class='low-opacity-font' >Income till date: #{song.income_till_date}</h5>") %>
        <% end %>
    </div><!-- end col-sm-5 view count -->
  </div><!-- end col-sm-offset-1 col-sm-10 -->
</div> <!-- end row -->

app/views/songs/_song_show_bottom.html.erb
<br/>
<br/>
<div class="col-md-offset-2 col-md-8">
<div class="row">

  <div class="col-sm-4">
    <a href="<%= new_song_path %>">
      <div class="signup-updates">
        <button class="btn btn-lg btn-transparent solid-button">
          <span id="updates">Add Song </span>
        </button>
      </div>
    </a>
  </div>



  <div class="col-sm-4">
    <a href="<%= album_song_path(song.album) %>">
      <div class="signup-updates">
        <button class="btn btn-lg btn-transparent solid-button">
          <span id="updates">Proceed To Checkout</span>
        </button>
      </div>
    </a>
  </div>
</div>
</div><!-- ends col-md-offset -->
<br/>
<br/>

app/views/songs/_song_show_public.html.erb
<div class="row">
  <div class="col-sm-offset-1 col-sm-10">
  <%= social_share_button_tag(@song.song_title) %>
    <h1>Details of song <%= song.song_title %> </h1>
    <div class="col-sm-5">
      <h5>Song Title</h5>
      <%= song.song_title %> <br/>

      <h5>Song Writer</h5>
      <% if song.self_written %>
        <%= raw("Self Written") %>
      <% else %>
        <%= raw("Original artist:") %>
        <%= song.original_artist %>
        <br/>
        <%= raw("Original song title:") %>
        <%= song.original_song_title %>
      <% end %>

       
        <br/>

      <h5>Album Name</h5>
      <%= song.album.album_name %> <br/>

      <h5>Song Duration</h5>
      <%= song.duration.strftime("%H:%M") if !song.duration.nil?%> <br/>

      <h5>Explicit Lyrics</h5>
      <% if song.explicit_lyrics %>
        <%= raw("Yes") %>
      <% else %>
        <%= raw("No") %>
      <% end %>
       
        <br/>

    </div>
    <div class="col-sm-7">
      <h5>Lyrics of the song</h5>
      <div id="lyrics-show">
      <%= song.lyrics %> <br/>
      </div>
    </div>
  </div>
</div>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>
<%= render partial: "form", locals: {song: @song} %>

app/views/songs/index.html.erb
<%= render "songs/secondheader" %>
<h1>List of Songs uploaded by User</h1>

<%# <%= @songs.last.song_title %>

app/views/songs/new.html.erb
<%= render "songs/secondheader" %>
<div class="row">
  <div class="col-sm-offset-1 col-sm-10">
    <h1 class="center-text" >Upload New Song</h1>
<%= render partial: "form", locals: {song: @song} %>
  </div>
</div>


<script type="text/javascript">
	$(document).ready(function(){
	  $("#song_self_written_true").change ( function(){
	    if($('#song_self_written_true').is(':checked')) { document.getElementById('cover_song').style.display = 'none'; }
	  });
	  $("#song_self_written_false").change ( function(){
	    if($('#song_self_written_false').is(':checked')) { document.getElementById('cover_song').style.display = 'block'; }
	  });
	})
</script>



<!-- 
      $("#cover_song").style['display'] = 'block';
    } 
    else {
      $("#cover_song").style['display'] = 'none';  -->

app/views/songs/show.html.erb
  <%= render "songs/secondheader" %>
  <%= raw("<div class='row'><div class='col-sm-offset-1 col-sm-10'>") %>
    
    <%= raw("</div></div>") %>
  <%= render partial: "songs/song_show", locals: {song: @song} %>
  <% if can? :create, Song %>
    <%= render partial: "songs/song_show_bottom", locals: {song: @song} %>
  <% end %>