config/routes.rb
Rails.application.routes.draw do
  

  resources :memberships, only: [:create]
  resources :shortlists, only: [:create, :destroy, :index]

  resources :song_stats do
      collection { post :import }
  end

  resources :transaction_logs
  resources :subscriptions, only: [:update, :destroy]
  resources :subscription_items, only: [:create, :update, :destroy]

  resources :songs do
    collection { get :all_index }
  end

  resources :albums

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
  resources :users, only: [:show, :update, :edit]

  get 'static_pages/home'
  get 'after_signup_home', to: "static_pages#after_signup_home"
  get 'inactive_signup_home', to: "static_pages#inactive_signup_home"
  get 'about', to: "static_pages#about"
  get 'faq', to: "static_pages#faq"
  get 'contact', to: "static_pages#contact"
  get 'updates', to: "static_pages#updates"
  get 'letter', to: "static_pages#letter"
  get 'pricing', to: "static_pages#pricing"
  get 'dashboard', to: "static_pages#dashboard"
  get 'terms', to: "static_pages#terms"
  get 'cart_page', to: "static_pages#cart_page"
  get 'payment_page', to: "static_pages#payment_page"
  get 'post_login_home', to: "static_pages#post_login_home"
  get 'discover', to: "static_pages#discover"
  get 'performance', to: "static_pages#performance"
  get 'wallet', to: "static_pages#wallet"
  get 'holdings', to: "static_pages#holdings"
  get 'opentrades', to: "static_pages#open_trades"

  get 'membership', to: "static_pages#membership"
  get 'renewals', to: "static_pages#renewals"

  resources :bids, only: [:create, :update, :destroy]
  resources :offers, only: [:create, :update, :destroy]

  root 'static_pages#home'
  get 'albums/:id/album_song' => 'albums#album_song_show', as: :album_song

  resources :payments, only: [:new, :create]
  post 'express_checkout' => 'payments#express_checkout', as: :express_checkout
  post 'confirm_withdrawl' => 'payments#confirm_withdrawl', as: :confirm_withdrawl
  get 'initiate_withdrawl_email_verification' => 'payments#initiate_withdrawl_email_verification', as: :initiate_withdrawl_email_verification

end

app/models/payment.rb
# == Schema Information
#
# Table name: payments
#
#  id                 :integer          not null, primary key
#  express_token      :string
#  express_payer_id   :string
#  wallet_id          :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  transaction_log_id :integer
#  paypal_id          :string
#  payment_type       :integer          default(1), not null
#  details            :text
#

PAYMENT_TYPE = { 1 => 'deposit', 2=> 'withdrawl', 3 => 'deposit by alphabeats'}
class Payment < ActiveRecord::Base

  attr_accessor :name, :country, :email, :phone, :address, :shipping, :amount, :ip
  belongs_to :wallet
  # belongs_to :transaction_log
  validates_numericality_of  :payment_type
  serialize :details

  has_one :transaction_log, as: :transactable, dependent: :destroy

    def get_payment_type
      PAYMENT_TYPE[self.payment_type]
    end

    module PaymentType
      DEPOSIT = 1
      WITHDRAWL = 2
      ALPHABEATS_DEPOSIT = 3
    end

    def purchase
      response = EXPRESS_GATEWAY.purchase(BigDecimal.new(self.amount)*100, express_purchase_options)
      # self.wallet.update(amount: new_wallet_amount)
      # cart.update_attribute(:purchased_at, Time.now) if response.success?
      response.success?
    end

    def express_token=(token)
      self[:express_token] = token
      if new_record? && !token.blank?
        # you can dump details var if you need more info from buyer
        details = EXPRESS_GATEWAY.details_for(token)
        self.express_payer_id = details.payer_id
        self.name = details.name
        self.country = details.info["Address"]["CountryName"]
        self.email = details.params["payer"]
        self.amount = details.params["amount"]
        self.phone = details.contact_phone
        self.address = details.address
        self.shipping = details.shipping
        self.details = details
      end
    end

    def self.verify_withdrawl(user, wallet, amount, paypal_id)
      begin
        ActiveRecord::Base.transaction do
          @payment = Payment.create!(wallet_id: wallet.id, paypal_id: paypal_id, payment_type: PaymentType::WITHDRAWL)
          @transactionLog= @payment.create_transaction_log(amount: amount.to_f, transaction_type: TransactionLog::TransactionType::WITHDRAWL_FROM_WALLET, transaction_status: TransactionLog::TransactionStatus::PENDING,  user_id: user.id)
          # @transactionLog= TransactionLog.create!(amount: amount.to_f, transaction_type: TransactionLog::TransactionType::WITHDRAWL_FROM_WALLET, transaction_status: TransactionLog::TransactionStatus::PENDING,  user_id: user.id)
          # @payment = Payment.create!(wallet_id: wallet.id, transaction_log_id: @transactionLog.id, paypal_id: paypal_id, payment_type: PaymentType::WITHDRAWL)
          new_wallet_amount = wallet.amount - amount.to_f
          wallet.update_attributes!(amount: new_wallet_amount)
        end
      rescue ActiveRecord::RecordInvalid => invalid
        return false
      end #end of begin
      TransactionLogMailer.withdrawl_email(user, @transactionLog, @payment).deliver_now 
      return @transactionLog
    end

    #This is the function which admin uses to remove pending withdrawl - Payment.confirm(transaction_id)
    def self.confirm(transaction_id)
      transaction = TransactionLog.find(transaction_id)
      if transaction.confirm_withdrawl
        puts "\n\n "
        puts "Withdrawl is confirmed"
        puts "\n\n "
      else
        puts "\n\n "
        puts "Withdrawl has failed"
        puts "\n\n "
      end
    end


    private

    def express_purchase_options
      {
        :ip => ip,
        :token => express_token,
        :payer_id => express_payer_id
      }
    end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def confirm_withdrawl
    session[:amount]=params[:amount]
    session[:paypal_id]=params[:paypal_id]
    if params[:amount].to_f > current_user.wallet.amount
      redirect_to wallet_path, alert: "You cannot withdraw more than the available balance: #{ current_user.reload.wallet.amount}"
    end
  end

  def initiate_withdrawl_email_verification
    @transactionlog = Payment.verify_withdrawl(current_user, current_user.wallet, session[:amount], session[:paypal_id])
    session[:amount]= nil
    session[:paypal_id]= nil
    if @transactionlog
      redirect_to transaction_log_path(@transactionlog), notice: "Please check your email and respond accordingly"
    else
      redirect_to wallet_path, alert: "Withdrawl has been unsuccessful. Please try again"
    end
  end

	def express_checkout
		response = EXPRESS_GATEWAY.setup_purchase(BigDecimal.new(params[:amount])*100,
			ip: request.remote_ip,
			return_url: new_payment_url,
			cancel_return_url: wallet_url,
			currency: "USD",
			allow_guest_checkout: true,
			items: [{name: "Add Money", description: "Adds money to wallet ", amount: BigDecimal.new(params[:amount])*100}]
		)
    # p response
    # puts response
		redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token)
	end

	def new
		@payment = Payment.new(:express_token => params[:token])
	end

	def create
    # byebug
    wallet_create_if_empty
		# @payment = Payment.build(:express_token => params[:payment][:express_token], :wallet_id => current_user.wallet.id)
		@payment = current_user.wallet.payments.build(:express_token => params[:payment][:express_token])
		# @order.ip = request.remote_ip
    @payment.ip = request.remote_ip

		if @payment.save
			if @payment.purchase # this is where we purchase the order. refer to the model method below
        # new_wallet_amount = current_user.wallet.amount + BigDecimal.new(params[:payment][:amount])
        new_wallet_amount = current_user.wallet.amount + BigDecimal.new(@payment.amount)
        # byebug
        current_user.wallet.update(amount: new_wallet_amount)
        @payment.create_transaction_log(amount: BigDecimal.new(@payment.amount), transaction_type: TransactionLog::TransactionType::FROM_BANK, transaction_status: TransactionLog::TransactionStatus::SUCCESS,  user_id: current_user.id)
				redirect_to wallet_path
			else
				render :action => "failure"
			end
		else
			render :action => 'new'
		end
	end

  private

  def payment_params
    params.require(:payment).permit(:express_token)
  end

end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/confirm_withdrawl.html.erb
<div class="container">
<div class="row">
  <h2>Please confirm the following details</h2>

  <p> Paypal account typed in: <%= session[:paypal_id] %> </p>
  <p>Amount being withdrawn:<%= session[:amount] %> </p>
  <p> Current Balance: <%= current_user.reload.wallet.amount %></p>
  <p>Balance after withdrawl: <%= current_user.reload.wallet.amount - session[:amount].to_f %></p>

<br><br>
  <div class="col-sm-6">
    <a href="<%= wallet_path %>" >
      <div class="signup-updates">
        <button class="btn btn-lg btn-transparent solid-button">
          <span id="updates">Change Details</span>
        </button>
      </div>
    </a>
  </div>

  <div class="col-sm-6">
    <a href="<%= initiate_withdrawl_email_verification_path %>" data-confirm="Have you verified all the details? Are you sure you want to continue? If you are unsure click on cancel">
      <div class="signup-updates">
        <button class="btn btn-lg btn-transparent solid-button" >
          <span id="updates">Initiate Email Verification</span>
        </button>
      </div>
    </a>
  </div>
  </div>
</div>

app/views/payments/new.html.erb
<div class="container">
  <div class="row">
    <%= form_for(@payment) do |f| %>
          <%= render partial: 'shared/error_messages', locals: {resource: @payment}  %>
        <%= f.hidden_field :express_token %>
        <h3> Payment Confirmation details </h3>
        <p>
          Your name:  <%= @payment.name %> <br/>
          Email: <%= @payment.email %><br/>
          Your country: <%= @payment.country %> <br/>
          Current Balance: <%= current_user.wallet.amount %>&nbsp;USD<br/>
          Amount: <%= @payment.amount %>&nbsp;USD<br/>
          Balance after payment: <%= current_user.wallet.amount + BigDecimal.new(@payment.amount) %>&nbsp;USD<br/>
        </p>

      <%= f.submit "Complete Payment", class: 'btn btn-transparent'  %> &nbsp;&nbsp;&nbsp;&nbsp; <%= link_to "Cancel and Make new Payment", wallet_path, class:"btn btn-md btn-transparent" %>
    <% end %>
</div>
</div>

app/views/payments/withdraw_money.html.erb
<div class="container">
<div class="row">
  <h2>Please confirm the following details</h2>

  <p> Paypal account typed in: <%= session[:paypal_id] %> </p>
  <p>Amount being withdrawn:<%= session[:amount] %> </p>
  <p> Current Balance: <%= current_user.reload.wallet.amount %></p>
  <p>Balance after withdrawl: <%= current_user.reload.wallet.amount - session[:amount].to_f %></p>

<br><br>
  <div class="col-sm-6">
    <a href="<%= wallet_path %>">
      <div class="signup-updates">
        <button class="btn btn-lg btn-transparent solid-button">
          <span id="updates">Change Details</span>
        </button>
      </div>
    </a>
  </div>

  <div class="col-sm-6">
    <a href="<%= cart_page_path %>">
      <div class="signup-updates">
        <button class="btn btn-lg btn-transparent solid-button">
          <span id="updates">Initiate Email Verification</span>
        </button>
      </div>
    </a>
  </div>
  </div>
</div>